name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:    
  build:
    strategy:
      matrix:
        os: [windows, ubuntu]
        version: [8, 11, '']
        vm: [hotspot, openj9]
    runs-on: ${{ matrix.os }}-latest
    env:
      OS: ${{ matrix.os }}
      JDK_VERSION: ${{ matrix.version }}
      JDK_TYPE: ${{ matrix.vm }}
    steps:

      - name: Install Ruby
        if: contains(matrix.os, 'windows') 
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install ruby

      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Dockerfile          
        run: ruby generate_dockerfile.rb
      
      - name: Build Image on Linux
        if: "!contains(matrix.os, 'windows')"
        run: docker build -t danysk/$JDK_TYPE-$JDK_VERSION .

      - name: Build Image on Windows
        if: contains(matrix.os, 'windows')
        run: C:\msys64\usr\bin\bash -c "docker build -t danysk/$JDK_TYPE-$JDK_VERSION ."
