name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu]
        version: [8, 11, '']
        vm: [hotspot, openj9]
    runs-on: ${{ matrix.os }}-latest
    env:
      OS: ${{ matrix.os }}
      JDK_VERSION: ${{ matrix.version }}
      JDK_TYPE: ${{ matrix.vm }}
      IMAGE_NAME: danysk/${{ matrix.vm }}-${{ matrix.version || 'latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Dockerfile
        run: ruby generate_dockerfile.rb
      - name: Build Image on Linux
        if: "!contains(matrix.os, 'windows')"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ github.repository_owner }}
        run: ./build.sh
      - name: Build Image on Windows
        if: contains(matrix.os, 'windows')
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ github.repository_owner }}
        run: |
          # add msys2 to the path so the correct exes are used
          $env:PATH="C:\msys64\usr\bin;${env:PATH}"
          C:\msys64\usr\bin\bash -c "./build.sh"
